services:
  airflow:
    image: apache/airflow
    container_name: airflow-standalone
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./../../airflow/dags:/opt/airflow/dags
    restart: unless-stopped

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
